# Versions of components
UGENTOO_VERSION = 1.0
UGENTOO_RELEASE = $(shell cat release)
#KERNEL_VANILLA_VERSION = 3.10.39
#KERNEL_CERNVM_RELEASE = 70
BB_UPSTREAM_VERSION = 1.20.2
BB_RELEASE = 1
CURL_UPSTREAM_VERSION = 7.32.0
CURL_RELEASE = 1
E2FSPROGS_UPSTREAM_VERSION = 1.42.8
E2FSPROGS_RELEASE = 2
KEXEC_UPSTREAM_VERSION = 2.0.4
KEXEC_RELEASE = 1
SFDISK_UPSTREAM_VERSION = 2.23
SFDISK_RELEASE = 1
CVMFS_UPSTREAM_VERSION = 2.1.18
CVMFS_RELEASE = 1
EXTRAS_VERSION = 0.8

GENTOO_INCREASE_RELEASE = 0

GENTOO_SYSTEM = HEAD
GENTOO_BRANCHES = devel
#IMAGE_FORMATS = ova
#CERNVM_BRANCHES = testing devel prod slc4 slc5
#IMAGE_FORMATS = iso hdd fat vdi vmdk tar.gz ova
IMAGE_FORMATS = hdd

# Set to one of CERNVM_BRANCHES by main Makefile
GENTOO_BRANCH =
IMAGE_FORMAT =

# Derived parameters
UGENTOO_STRONG_VERSION = $(UGENTOO_VERSION).gentoo.x86_64
#KERNEL_VERSION = $(KERNEL_VANILLA_VERSION)-$(KERNEL_CERNVM_RELEASE)
KERNEL_STRONG_VERSION = 3.10.25-aufs
BB_VERSION = $(BB_UPSTREAM_VERSION)-$(BB_RELEASE)
BB_STRONG_VERSION = $(BB_VERSION).gentoo.x86_64
CURL_VERSION = $(CURL_UPSTREAM_VERSION)-$(CURL_RELEASE)
CURL_STRONG_VERSION = $(CURL_VERSION).gentoo.x86_64
E2FSPROGS_VERSION = $(E2FSPROGS_UPSTREAM_VERSION)-$(E2FSPROGS_RELEASE)
E2FSPROGS_STRONG_VERSION = $(E2FSPROGS_VERSION).gentoo.x86_64
KEXEC_VERSION = $(KEXEC_UPSTREAM_VERSION)-$(KEXEC_RELEASE)
KEXEC_STRONG_VERSION = $(KEXEC_VERSION).gentoo.x86_64
#$(SFDISK_UPSTREAM_VERSION)-$(SFDISK_RELEASE)
SFDISK_STRONG_VERSION = $(SFDISK_VERSION).gentoo.x86_64
CVMFS_VERSION = $(CVMFS_UPSTREAM_VERSION)-$(CVMFS_RELEASE)
CVMFS_STRONG_VERSION = $(CVMFS_VERSION).gentoo.x86_64
EXTRAS_STRONG_VERSION = $(EXTRAS_VERSION).gentoo.x86_64

#CERNVM_SERVER = $(shell grep ^$(CERNVM_BRANCH) branch2server | awk '{print $$2}')
#CERNVM_REPOSITORY = cernvm-$(CERNVM_BRANCH).cern.ch
GENTOO_ROOTTREE = ugentoo-root-$(GENTOO_BRANCH).$(UGENTOO_STRONG_VERSION).$(IMAGE_FORMAT)
IMAGE_DIR = ugentoo-images.$(UGENTOO_STRONG_VERSION)
IMAGE_NAME = ugentoo-$(GENTOO_BRANCH).$(UGENTOO_STRONG_VERSION)
IMAGE_FILE = $(IMAGE_NAME).$(IMAGE_FORMAT)
